# Databricks notebook source
# MAGIC %sql
# MAGIC USE CATALOG inv_risk_mgmt;
# MAGIC USE SCHEMA bronze;
# MAGIC DROP TABLE IF EXISTS FINANCING_ACCOUNTS;
# MAGIC CREATE TABLE FINANCING_ACCOUNTS
# MAGIC (
# MAGIC     ACCOUNT_ID INT,
# MAGIC     CUSTOMER_ID INT,
# MAGIC     BRANCH_ID INT,
# MAGIC     BUSINESS_UNIT_ID INT,
# MAGIC     PRODUCT_ID INT,
# MAGIC     CL_CATEGORY_ID INT,
# MAGIC     ACCOUNT_NO STRING,
# MAGIC     OPEN_DATE DATE,
# MAGIC     EXPIRY_DATE DATE,
# MAGIC     CLOSE_DATE DATE,
# MAGIC     ACCOUNT_STATUS STRING,
# MAGIC     SANCTION_AMOUNT DOUBLE,
# MAGIC     OUTSTANDING_AMT DOUBLE,
# MAGIC     PRINCIPAL_BALANCE DOUBLE,
# MAGIC     ACC_PROFIT_RATE FLOAT,
# MAGIC     IS_INSTALLMENT INT,
# MAGIC     DPD INT,
# MAGIC     CL_STATUS STRING,
# MAGIC     CREATED_AT TIMESTAMP,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;