# Databricks notebook source
# MAGIC %sql
# MAGIC USE CATALOG inv_risk_mgmt;
# MAGIC USE SCHEMA bronze;
# MAGIC CREATE TABLE IF NOT EXISTS DIVISIONS(
# MAGIC     DIVISION_ID INT,
# MAGIC     DIVISION_NAME STRING,
# MAGIC     LAST_UPDATE_TIME TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC ) USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DISTRICTS(
# MAGIC     DISTRICT_ID INT,
# MAGIC     DISTRICT_NAME STRING,
# MAGIC     DIVISION_ID INT,
# MAGIC     LAST_UPDATE_TIME TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC ) USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS THANAS(
# MAGIC     THANA_ID INT,
# MAGIC     THANA_NAME STRING,
# MAGIC     DISTRICT_ID INT,
# MAGIC     LAST_UPDATE_TIME TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC ) USING DELTA;
# MAGIC
# MAGIC --drop TABLE IF EXISTS branches;
# MAGIC CREATE TABLE IF NOT EXISTS branches
# MAGIC (
# MAGIC     branch_id INT,
# MAGIC     branch_name STRING,
# MAGIC     address STRING,
# MAGIC     thana_id INT,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CL_CATEGORIES
# MAGIC (
# MAGIC     CL_CATEGORY_ID INT,
# MAGIC     CL_CODE STRING,
# MAGIC     DESCRIPTION STRING,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS BUSINESS_UNITS
# MAGIC (
# MAGIC     BUSINESS_UNIT_ID INT,
# MAGIC     BUSINESS_UNIT_NAME STRING,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_TYPES
# MAGIC (
# MAGIC     CUSTOMER_TYPE_ID INT,
# MAGIC     CUSTOMER_TYPE STRING,
# MAGIC     DESCRIPTION STRING,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMERS
# MAGIC (
# MAGIC     CUSTOMER_ID INT,
# MAGIC     CUSTOMER_TYPE_ID INT,
# MAGIC     CUSTOMER_NAME STRING,
# MAGIC     CUSTOMER_RISK_LEVEL STRING,
# MAGIC     ADDRESS STRING,
# MAGIC     EMAIL STRING,
# MAGIC     MOBILE STRING,
# MAGIC     BRANCH_ID INT,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS INDUSTRIES
# MAGIC (
# MAGIC     INDUSTRY_ID INT,
# MAGIC     SECTOR_NAME STRING,
# MAGIC     SUB_SECTOR_NAME STRING,
# MAGIC     RISK_CATEGORY STRING,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS FINANCING_PRODUCTS
# MAGIC (
# MAGIC     PRODUCT_ID INT,
# MAGIC     PRODUCT_CODE STRING,
# MAGIC     PRODUCT_NAME STRING,
# MAGIC     PRODUCT_TYPE STRING,
# MAGIC     INSTALLMENT_BASED INT,
# MAGIC     INDUSTRY_ID INT,
# MAGIC     PERSONAL_FINANCING INT,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC DROP TABLE IF EXISTS FINANCING_ACCOUNTS;
# MAGIC CREATE TABLE IF NOT EXISTS FINANCING_ACCOUNTS
# MAGIC (
# MAGIC     ACCOUNT_ID INT,
# MAGIC     CUSTOMER_ID INT,
# MAGIC     BRANCH_ID INT,
# MAGIC     BUSINESS_UNIT_ID INT,
# MAGIC     PRODUCT_ID INT,
# MAGIC     CL_CATEGORY_ID INT,
# MAGIC     ACCOUNT_NO STRING,
# MAGIC     OPEN_DATE DATE,
# MAGIC     EXPIRY_DATE DATE,
# MAGIC     CLOSE_DATE DATE,
# MAGIC     ACCOUNT_STATUS STRING,
# MAGIC     SANCTION_AMOUNT DOUBLE,
# MAGIC     OUTSTANDING_AMT DOUBLE,
# MAGIC     PRINCIPAL_BALANCE DOUBLE,
# MAGIC     ACC_PROFIT_RATE FLOAT,
# MAGIC     IS_INSTALLMENT INT,
# MAGIC     CL_STATUS STRING,
# MAGIC     CREATED_AT TIMESTAMP,
# MAGIC     last_update_time TIMESTAMP,
# MAGIC
# MAGIC     ingestion_time TIMESTAMP,
# MAGIC     source_file STRING
# MAGIC )
# MAGIC USING DELTA;