# Databricks notebook source
# MAGIC %sql
# MAGIC USE CATALOG inv_risk_mgmt;
# MAGIC USE SCHEMA gold;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_BRANCH
# MAGIC (
# MAGIC     branch_id INT,
# MAGIC     branch_name STRING,
# MAGIC     address STRING,
# MAGIC     thana_name STRING,
# MAGIC     district_name STRING,
# MAGIC     division_name STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_CL_CATEGORY
# MAGIC (
# MAGIC     CL_CATEGORY_ID INT,
# MAGIC     CL_CODE STRING,
# MAGIC     DESCRIPTION STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_BUSINESS_UNIT
# MAGIC (
# MAGIC     BUSINESS_UNIT_ID INT,
# MAGIC     BUSINESS_UNIT_NAME STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_CUSTOMER
# MAGIC (
# MAGIC     CUSTOMER_ID INT,
# MAGIC     CUSTOMER_TYPE_ID INT,
# MAGIC     CUSTOMER_NAME STRING,
# MAGIC     CUSTOMER_TYPE STRING,
# MAGIC     CUSTOMER_RISK_LEVEL STRING,
# MAGIC     ADDRESS STRING,
# MAGIC     EMAIL STRING,
# MAGIC     MOBILE STRING,
# MAGIC     BRANCH_ID INT
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_INDUSTRY
# MAGIC (
# MAGIC     INDUSTRY_ID INT,
# MAGIC     SECTOR_NAME STRING,
# MAGIC     SUB_SECTOR_NAME STRING,
# MAGIC     RISK_CATEGORY STRING
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DIM_FINANCING_PRODUCT
# MAGIC (
# MAGIC     PRODUCT_ID INT,
# MAGIC     PRODUCT_CODE STRING,
# MAGIC     PRODUCT_NAME STRING,
# MAGIC     PRODUCT_TYPE STRING,
# MAGIC     INSTALLMENT_BASED INT,
# MAGIC     INDUSTRY_ID INT
# MAGIC )
# MAGIC USING DELTA;
# MAGIC
# MAGIC DROP TABLE IF EXISTS FACT_FINANCING_ACCOUNT;
# MAGIC CREATE TABLE IF NOT EXISTS FACT_FINANCING_ACCOUNT
# MAGIC (
# MAGIC     ACCOUNT_ID INT,
# MAGIC     CUSTOMER_ID INT,
# MAGIC     BRANCH_ID INT,
# MAGIC     BUSINESS_UNIT_ID INT,
# MAGIC     PRODUCT_ID INT,
# MAGIC     CL_CATEGORY_ID INT,
# MAGIC     ACCOUNT_NO STRING,
# MAGIC     OPEN_DATE DATE,
# MAGIC     EXPIRY_DATE DATE,
# MAGIC     CLOSE_DATE DATE,
# MAGIC     ACCOUNT_STATUS STRING,
# MAGIC     SANCTION_AMOUNT DOUBLE,
# MAGIC     OUTSTANDING_AMT DOUBLE,
# MAGIC     PRINCIPAL_BALANCE DOUBLE,
# MAGIC     ACC_PROFIT_RATE FLOAT,
# MAGIC     IS_INSTALLMENT INT,
# MAGIC     DPD INT,
# MAGIC     CL_STATUS STRING,
# MAGIC     CREATED_AT TIMESTAMP
# MAGIC )
# MAGIC USING DELTA;